### ISSUE TITLE
Akinator librarory not working

### ISSUE THREAD

**Issue by adamharsh** [NinjaSnail1080/akinator.py#10]
I have tried akinator with all the three versions i.e 
1. akinator.py
2. akinator.py[async]
3. akinator.py[fast_async]

but nothing is working for me. I am using Python 3.7. I checked for every possible case from my end but nothing worked.

Following is the result with akinator.py[async]
![image](https://user-images.githubusercontent.com/26489133/80782330-4b6b5480-8b93-11ea-9a64-9054c21aaf16.png)

Can you please help me with this.

**Comment by AlexZeGamer** [comment]
I still get the same error with akinator.py[async]. I tried different servers/languages...
`ClientConnectorError: Cannot connect to host srv14.akinator.com:9281 ssl:default [Connect call failed ('147.135.138.229', 9281)]`

**Comment by NinjaSnail1080** [comment]
The library has been updated. Sorry it took so long, but it should be working now.
