### ISSUE TITLE
Was working perfectly, now receiving JSON Decode error.

### ISSUE THREAD

**Issue by DinozavrNenarkoman** [NinjaSnail1080/akinator.py#14]
Hey there, and thanks for this awesome module, we was using it for our bot, but today its making decode error like in the past.

We did not changed any of our bot code, so everything was working perfectly until now, maybe something in the akinator logic was updated or changed, could you please take a look how to fix it?

Here is exception we are receiving, also sorry for the messy lining in the code, we just ripped it from our log.

```
Nov  4 22:16:44     akigame=aki.start_game(language='ru')
Nov  4 22:16:44     resp = self._parse_response(r.text)
Nov  4 22:16:44     akinator.py", line 91, in _parse_response
Nov  4 22:16:44     return json.loads(",".join(response.split("(")[1::])[:-1])
Nov  4 22:16:44   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
Nov  4 22:16:44     return _default_decoder.decode(s)
Nov  4 22:16:44   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
Nov  4 22:16:44     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Nov  4 22:16:44   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
Nov  4 22:16:44     raise JSONDecodeError("Expecting value", s, err.value) from None
Nov  4 22:16:44     json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Nov  4 22:16:44 
Nov  4 22:16:44    During handling of the above exception, another exception occurred:
```

**Comment by NinjaSnail1080** [comment]
This is really strange, cause I just tested it and it's working fine for me. Are you using the most recent version?

**Comment by DinozavrNenarkoman** [comment]
> This is really strange, cause I just tested it and it's working fine for me. Are you using the most recent version?

Hello and yes, double checked, and even tried to reinstall now, same error happens on starting.
It was working fine just two days ago, no single line of code or environment was changed, what could trigger this issue?

**Comment by DinozavrNenarkoman** [comment]
Look also here, maybe we are doing something wrong with reinstall?
We are using pip to install it, should we also try to reinstall all requirements?

```
Collecting akinator.py
  Downloading https://files.pythonhosted.org/packages/28/a8/ff5e29dcc968b84ae45cbb13d896afbc74962a98e1b3633b7309697b981b/akinator.py-4.0.1-py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (from akinator.py) (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests->akinator.py) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.8/site-packages (from requests->akinator.py) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests->akinator.py) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests->akinator.py) (2019.9.11)
Installing collected packages: akinator.py
Successfully installed akinator.py-4.0.1
```

**Comment by NinjaSnail1080** [comment]
It seems the problem is that it can't parse the response for whatever reason. After line 165 in `akinator/akinator.py`, insert the line:
```
print(r.text)
```
and tell me what the output is

**Comment by DinozavrNenarkoman** [comment]
This is the output of the print.

`{"completion":"KO - UNAUTHORIZED","url":"https:\/\/play.google.com\/store\/apps\/details?id=com.digidust.elokence.akinator.freemium"}
`

**Comment by DinozavrNenarkoman** [comment]
> It seems the problem is that it can't parse the response for whatever reason. After line 165 in `akinator/akinator.py`, insert the line:
> 
> ```
> print(r.text)
> ```
> 
> and tell me what the output is

Hey there, is there anything new about the issue?

Also just checked now and something different happens now, also important info, we are using RU language at game start, seems in EN it does works fine now, but was erroring few days ago.

For the first question after start game in "ru" lang, it prints out this.
`https://ru.akinator.com`
Seems something went wrong and it does just prints site name instead of first question, and game gets stuck in this part.
Hope this info helps you.

**Comment by DinozavrNenarkoman** [comment]
Hello there, any info about this? Sadly but it is still not working for us, reinstall doesn't help, is this abandoned?

**Comment by NinjaSnail1080** [comment]
I tested it again with all languages and it still works completely fine for me. I'm sorry but I have no idea why Russian doesn't work for you.

**Comment by AlexZeGamer** [comment]
It doesn't happen all the time but still enough for it to be annoying 😕
It happened more than 3.2% of the time on the 3500 games played on my bot during december with the last version of akinator.py (mostly playing in french but I think the language doesn't really matter)

**Comment by AlexZeGamer** [comment]
This error still occurs very frequently on my bot which runs hundreds of games each days...

**Comment by NinjaSnail1080** [comment]
The latest update should fix this issue
