### ISSUE TITLE
Bad auth

### ISSUE THREAD

**Issue by Kyle2142** [NinjaSnail1080/akinator.py#2]
Not sure if this is 3.7 specific but trying to answer the first question gives me bad auth error:
```
In [1]: from akinator import Akinator

In [2]: a = Akinator()

In [3]: a.start_game()
Out[3]: 'Is your character a female?'

In [4]: a.answer("no")
-------------------------------------------------------
AkiFailedToConnect    Traceback (most recent call last)
<ipython-input-4-e208fb04bb8b> in <module>
----> 1 a.answer("no")

~/.local/lib/python3.7/site-packages/akinator/akinator.py in answer(self, ans)
    135             raise AkiNoQuestions("\"Akinator.step\" reached 80. No more questions")
    136         else:
--> 137             raise AkiFailedToConnect("Failed to connect: {}".format(resp["completion"]))
    138
    139     def back(self):

AkiFailedToConnect: Failed to connect: KO - BAD AUTH
```
Python 3.7 via ipython on a Google cloud VPS as well as my raspberry pi at home.
waiting a little and trying again gives a timeout

**Comment by NinjaSnail1080** [comment]
Perfect timing because I just updated the library to version 1.1.0 to use the new Akinator API since the old way doesn't work anymore (they changed how you request things; it's a bit more complicated now). Anyway, now it should work for you
