### ISSUE TITLE
Connection gets closed between games

### ISSUE THREAD

**Issue by 007Gamerx** [NinjaSnail1080/akinator.py#22]
LOGS:
      Unclosed client session
      client_session: <aiohttp.client.ClientSession object at 0x7f09ac4d9a00>
      Unclosed connector
      connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f09ac1fa580>, 825958.029426889)]']
      connector: <aiohttp.connector.TCPConnector object at 0x7f09ac998970

While playing the game akinator stops randomly in between . And I see the above error in logs. 
Hoping for quick response.

![image](https://user-images.githubusercontent.com/83570845/132868770-828308ec-555c-4f89-bab7-3366f2c111fe.png)

**Comment by 007Gamerx** [comment]
ALSO I USE ASYNC library 
And I integrated it with discord bot as seen in picture.

**Comment by NinjaSnail1080** [comment]
Strange. Are you specifying a ClientSession object in the start_game function or are you leaving it as None?

**Comment by 007Gamerx** [comment]
> Strange. Are you specifying a ClientSession object in the start_game function or are you leaving it as None?

Nope , I am not specifying. Its default

**Comment by NinjaSnail1080** [comment]
Are you calling a new instance of the Akinator class every time the command is run? Cause someone before made the mistake of not doing that, meaning multiple akinator games running at the same time could interfere with each other since they'd all shared the same class.

**Comment by 007Gamerx** [comment]
> Are you calling a new instance of the Akinator class every time the command is run? Cause someone before made the mistake of not doing that, meaning multiple akinator games running at the same time could interfere with each other since they'd all shared the same class.

Yep! Everytime a command is run a new instance is created. I will share my code in a moment.

Moreover this issue also occurs even if only one person plays at the time

**Comment by NinjaSnail1080** [comment]
Very strange. In that case, I'll wait to see your code

**Comment by 007Gamerx** [comment]
https://www.pastiebin.com/613c2c9867349
Aight heres my code. It's a mess lol. I tried to explain things using comments.
Hope you get that!

**Comment by NinjaSnail1080** [comment]
So when you say the game stops randomly in between, does that mean it just stops responding to answers and ends the game, forcing the player to start a new game?

**Comment by 007Gamerx** [comment]
> So when you say the game stops randomly in between, does that mean it just stops responding to answers and ends the game, forcing the player to start a new game?

Yes

**Comment by NinjaSnail1080** [comment]
That makes me think it's a problem with the bot, not the library. I noticed that you forgot to await the `aki.close()` function in line 23. I don't know if that's what's causing your problem, but it's worth a shot.

**Comment by 007Gamerx** [comment]
> That makes me think it's a problem with the bot, not the library. I noticed that you forgot to await the `aki.close()` function in line 23. I don't know if that's what's causing your problem, but it's worth a shot.

YEAH I forgot await. But that doesn't fixed the problem :(

**Comment by NinjaSnail1080** [comment]
Still, I'm almost positive that this is an issue with the bot or something else, not this library. No one else has reported a problem similar to this. Maybe it's a network issue? I don't know.

I'll close this issue for now. If someone reports a problem similar to yours, I'll take another look. But I'm almost certain that this problem is being caused on your end. Maybe it's an issue with the bot's code or maybe it's something else, like a network issue.
