### ISSUE TITLE
Support for Multiple Language Options

### ISSUE THREAD

**Issue by Pysics** [NinjaSnail1080/akinator.py#24]
On the [akinator website](https://akinator.com/), changing the language also changes option names. This is not currently supported in this library. Something like this could be added:
```python
aki = akinator.Akinator()
q = aki.start_game(language="fr")
options = q.options
# {"yes": "oui", "no": "non"...}
```

**Comment by Pysics** [comment]
@NinjaSnail1080 Is this possible?

**Comment by NinjaSnail1080** [comment]
Yes, but I don't think it's necessary. The user can just use the integers 1-4 to specify an option, and that is in fact how it works in the API. The other possible option names are just there in the wrapper for convenience's sake, and I don't think it's worth adding a bunch more option names for each language
