### ISSUE TITLE
How can I add a `Continue` option?

### ISSUE THREAD

**Issue by Pysics** [NinjaSnail1080/akinator.py#26]
This is the code as seen in `README.md`:

```python
import akinator

aki = akinator.Akinator()

q = aki.start_game()

while aki.progression <= 80:
    a = input(q + "\n\t")
    if a == "b":
        try:
            q = aki.back()
        except akinator.CantGoBackAnyFurther:
            pass
    else:
        q = aki.answer(a)
aki.win()

correct = input(f"It's {aki.first_guess['name']} ({aki.first_guess['description']})! Was I correct?\n{aki.first_guess['absolute_picture_path']}\n\t")
if correct.lower() == "yes" or correct.lower() == "y":
    print("Yay\n")
else:
    print("Oof\n")
```

@NinjaSnail1080 How can I change it such that instead of printing `Oof`, it asks if you want to continue?

**Comment by NinjaSnail1080** [comment]
You'd want to use nested while loops. The innermost loop would be something like `while aki.progression <= target_progress:`, where target_progress is a variable set to 80 or whatever, then in the outer loop (`while True:` would suffice), you ask if the player wants to continue. If they do, change target_progress to like 95 and it'll continue. Just make sure to break out of the outer loop when the game is over.

There's an example in my old discord bot: https://github.com/NinjaSnail1080/MATs-Bot/blob/master/cogs/fun.py#L147. That leads to the command function, but the main code for the akinator game starts at line 202 in the `play_akinator` function
