### ISSUE TITLE
KO - BAD REQUEST 1

### ISSUE THREAD

**Issue by TollyThaWally** [NinjaSnail1080/akinator.py#8]
Every time I try and start an akinator game, the following error occurs:
```
Traceback (most recent call last):
  File "bot.py", line 3965, in on_message
    q = await aki.start_game(akiLangCode)
  File "/usr/local/lib/python3.7/site-packages/akinator/async_aki/async_akinator.py", line 136, in start_game
    return raise_connection_error(resp["completion"])
  File "/usr/local/lib/python3.7/site-packages/akinator/utils.py", line 132, in raise_connection_error
    raise AkiConnectionFailure("An unknown error has occured. Server response: {}".format(response))
akinator.exceptions.AkiConnectionFailure: An unknown error has occured. Server response: KO - BAD REQUEST 1
```

Edit: The servers have also changed, to see this error you need to change to the correct server

**Comment by TollyThaWally** [comment]
Is anyone else having this issue? I haven't changed any code so I'm guessing that the way Akinator works internally must have changed. Is this library going to be updated?

**Comment by srevinsaju** [comment]
Yes, I had the same issue few weeks ago. Now nothings working

**Comment by NinjaSnail1080** [comment]
The library has been updated. Sorry it took so long
